#!/bin/bash

export PATH="/usr/local/bin:$PATH"

INSTANCE_ID=$(uuidgen)

SCRIPT_PATH=$HOME/.config/.commands/PrinceAlfredsLogic.py


wezterm start --always-new-process --class "WezTerm-$INSTANCE_ID" -- python3 $SCRIPT_PATH &

WEZTERM_PID=$!

echo wezterm pid $WEZTERM_PID

sleep 0.2

osascript <<EOF
tell application "WezTerm"
    activate
    delay 0.1
    set frontmost to true
end tell
EOF

wait $WEZTERM_PID

echo "WezTerm has exited. Complete."

exit 0
