#!/bin/bash

visible_apps=$(osascript <<EOF
tell application "System Events"
    set appList to name of every application process whose visible is true
end tell
return appList
EOF
)
visible_apps=$(echo "$visible_apps" | sed 's/, /\n/g')
selected_app=$(echo -e "$visible_apps" | fzf)

if [ -n "$selected_app" ]; then
    killall "$selected_app"
    echo "$selected_app has been force quit."
else
    echo "No application selected."
fi
