#!/bin/bash

osascript <<EOF
tell application "Safari"
    set spotifyTabOpen to false
    set windowList to windows
    repeat with currentWindow in windowList
        set tabList to tabs of currentWindow
        repeat with currentTab in tabList
            if (URL of currentTab contains "open.spotify.com") then
                set spotifyTabOpen to true
                tell currentWindow to set current tab to currentTab
                activate
                exit repeat
            end if
        end repeat
        if spotifyTabOpen is true then
            exit repeat
        end if
    end repeat
end tell

EOF
